services:
  postgresdb0:
    container_name: postgresdb0
    image: postgres:alpine
    restart: always

    environment:
      POSTGRES_USER: postgresdb0
      POSTGRES_PASSWORD: password

    volumes:
      - /db-data/postgres:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  pg-admin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_LISTEN_PORT: 5050

    ports:
      - "5050:5050"

networks:
  default:
    name: common
    external: true
